version: "3.8"

services:

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - 8080:80

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 8005:8005

  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    depends_on:
      - mongo
    ports:
      - 8887:8887
    environment:
      WAIT_HOSTS: mongo:27017

  mongo:
    container_name: mongo
    image: mongo:4.4.5
    ports:
      - 27017:27017
