import ObjectId from 'bson-objectid';
import {
  DataType,
  LabelTaskType,
  ProcessType,
  WorkflowEdge,
  WorkflowNode,
  WorkflowNodeType,
} from '../types';

export default {
  nodes: [
    {
      id: 'node-47353599',
      title: 'initialization',
      type: WorkflowNodeType.Initialization,
      value: {
        dataType: DataType.Image,
        labelTasks: [LabelTaskType.Classification],
      },
      x: 25,
      y: 25,
    },
    {
      id: 'node-37008559',
      title: 'SVD features',
      type: WorkflowNodeType.FeatureExtraction,
      value: {
        type: ProcessType.FeatureExtraction,
        name: 'SVD (Unsupervised)',
        id: 'image-SVD-25940167',
        inputs: ['dataObjects'],
        isAlgorithmic: true,
        isBuiltIn: true,
        isModelBased: false,
        isServerless: false,
        api: 'http://localhost:8005/features/image/SVD',
      },
      x: 145,
      y: 25,
    },
    {
      id: 'node-6411710',
      title: 'projection + clustering',
      type: WorkflowNodeType.DataObjectSelection,
      value: [{
        type: ProcessType.DataObjectSelection,
        name: 'Projection (User Sampling)',
        id: 'Projection',
        inputs: ['features', 'labels'],
        isAlgorithmic: false,
        isBuiltIn: true,
        isModelBased: false,
        isServerless: true,
        api: 'Projection',
      }, {
        type: ProcessType.DataObjectSelection,
        name: 'Cluster (Clustering)',
        id: 'Cluster-13466955',
        inputs: ['features', 'labels'],
        isAlgorithmic: true,
        isBuiltIn: true,
        isModelBased: false,
        isServerless: false,
        api: 'http://localhost:8005/selection/Cluster',
        params: {
          nBatch: {
            value: 16,
            title: 'Selection Batch Size',
            options: [
              { value: 1, text: '1' },
              { value: 4, text: '4' },
              { value: 16, text: '16' },
              { value: 32, text: '32' },
              { value: 48, text: '48' },
              { value: 64, text: '64' },
              { value: 96, text: '96' },
            ],
          },
        },
      }],
      x: 265,
      y: 25,
    },
    {
      id: 'node-86803967',
      title: 'decision tree prelabel',
      type: WorkflowNodeType.DefaultLabeling,
      value: {
        type: ProcessType.DefaultLabeling,
        name: 'ModelPrediction',
        id: 'ModelPrediction-29967546',
        inputs: ['features', 'model'],
        isAlgorithmic: true,
        isBuiltIn: true,
        isModelBased: true,
        isServerless: false,
        model: {
          type: 'DecisionTree',
          name: 'DecisionTree (Supervised)',
          objectId: (new ObjectId('DecisionTree')).toHexString(),
          isBuiltIn: true,
          isServerless: false,
          isValidSampler: false,
        },
        api: 'http://localhost:8005/defaultLabels/ModelPrediction',
      },
      x: 385,
      y: 25,
    },
    {
      id: 'node-63746075',
      title: 'direct labeling',
      type: WorkflowNodeType.TaskTransformation,
      value: {
        type: ProcessType.TaskTransformation,
        name: 'DirectLabeling',
        id: 'DirectLabeling-97377357',
        inputs: ['dataObjects', 'labelTask', 'labelSpace'],
        isAlgorithmic: true,
        isBuiltIn: true,
        isModelBased: false,
        isServerless: true,
      },
      x: 505,
      y: 25,
    },
    {
      id: 'node-44216216',
      title: 'grid matrix',
      type: WorkflowNodeType.InteractiveLabeling,
      value: [{
        type: ProcessType.InteractiveLabeling,
        name: 'Grid Matrix',
        id: 'Grid-Matrix',
        inputs: ['dataObjects', 'samples'],
        isAlgorithmic: false,
        isBuiltIn: true,
        isModelBased: false,
        isServerless: true,
        params: {
          nRows: {
            value: 4,
            title: 'Number of Objects per Column',
            options: [
              { value: 1, text: '1' },
              { value: 2, text: '2' },
              { value: 4, text: '4' },
              { value: 6, text: '6' },
              { value: 8, text: '8' },
            ],
          },
          nColumns: {
            value: 4,
            title: 'Number of Objects per Row',
            options: [
              { value: 1, text: '1' },
              { value: 4, text: '4' },
              { value: 8, text: '8' },
              { value: 12, text: '12' },
            ],
          },
        },
      }],
      x: 625,
      y: 25,
    },
    {
      id: 'node-70767097',
      title: 'check all labeled',
      type: WorkflowNodeType.StoppageAnalysis,
      value: {
        type: ProcessType.StoppageAnalysis,
        name: 'AllChecked',
        id: 'AllChecked-46322013',
        inputs: ['labels'],
        isAlgorithmic: true,
        isBuiltIn: true,
        isModelBased: false,
        isServerless: true,
        api: 'AllChecked',
      },
      x: 745,
      y: 25,
    },
    {
      id: 'node-69466632',
      title: 'stop?',
      type: WorkflowNodeType.Decision,
      x: 745,
      y: 115,
    },
    {
      id: 'node-29117539',
      title: 'exit',
      type: WorkflowNodeType.Terminal,
      x: 745,
      y: 205,
    },
    {
      id: 'node-14283634',
      title: 'interim model training',
      type: WorkflowNodeType.InterimModelTraining,
      value: {
        type: ProcessType.InterimModelTraining,
        name: 'Retrain',
        id: 'Retrain-16440841',
        inputs: ['features', 'labels', 'model'],
        isAlgorithmic: true,
        isBuiltIn: true,
        isModelBased: false,
        isServerless: false,
        api: 'http://localhost:8005/modelUpdated/Retrain',
      },
      x: 265,
      y: 115,
    },
  ],
  edges: [
    {
      source: 'node-47353599',
      target: 'node-37008559',
      x1: 105,
      y1: 55,
      x2: 145,
      y2: 55,
    },
    {
      source: 'node-37008559',
      target: 'node-6411710',
      x1: 225,
      y1: 55,
      x2: 265,
      y2: 55,
    },
    {
      source: 'node-6411710',
      target: 'node-86803967',
      x1: 345,
      y1: 55,
      x2: 385,
      y2: 55,
    },
    {
      source: 'node-86803967',
      target: 'node-63746075',
      x1: 465,
      y1: 55,
      x2: 505,
      y2: 55,
    },
    {
      source: 'node-63746075',
      target: 'node-44216216',
      x1: 585,
      y1: 55,
      x2: 625,
      y2: 55,
    },
    {
      source: 'node-44216216',
      target: 'node-70767097',
      x1: 705,
      y1: 55,
      x2: 745,
      y2: 55,
    },
    {
      source: 'node-70767097',
      target: 'node-69466632',
      x1: 785,
      y1: 85,
      x2: 785,
      y2: 115,
    },
    {
      source: 'node-69466632',
      target: 'node-29117539',
      x1: 745,
      y1: 145,
      x2: 345,
      y2: 145,
      condition: true,
    },
    {
      source: 'node-69466632',
      target: 'node-14283634',
      x1: 785,
      y1: 175,
      x2: 785,
      y2: 205,
      condition: false,
    },
    {
      source: 'node-14283634',
      target: 'node-6411710',
      x1: 305,
      y1: 115,
      x2: 305,
      y2: 85,
    },
  ],
} as {
  nodes: WorkflowNode[],
  edges: WorkflowEdge[],
};
