import {
  DataType,
  LabelTaskType,
  ProcessType,
  WorkflowGraph,
  WorkflowNodeType,
} from '../types';

export default {
  nodes: [
    {
      id: 'node-47353599',
      title: 'initialization',
      type: WorkflowNodeType.Initialization,
      value: {
        dataType: DataType.Image,
        labelTasks: [LabelTaskType.Classification],
      },
      x: 25,
      y: 25,
    },
    {
      id: 'node-6411710',
      title: 'random sampling',
      type: WorkflowNodeType.DataObjectSelection,
      value: [{
        type: ProcessType.DataObjectSelection,
        name: 'Random (Dummy)',
        id: 'Random-73417867',
        inputs: ['labels'],
        isAlgorithmic: true,
        isBuiltIn: true,
        isModelBased: false,
        isServerless: true,
        api: 'Random',
        params: {
          nBatch: {
            value: 16,
            title: 'Selection Batch Size',
            options: [
              { value: 1, text: '1' },
              { value: 4, text: '4' },
              { value: 16, text: '16' },
              { value: 32, text: '32' },
              { value: 48, text: '48' },
              { value: 64, text: '64' },
              { value: 96, text: '96' },
            ],
          },
        },
      }],
      x: 145,
      y: 25,
    },
    {
      id: 'node-63746075',
      title: 'direct labeling',
      type: WorkflowNodeType.TaskTransformation,
      value: {
        type: ProcessType.TaskTransformation,
        name: 'DirectLabeling',
        id: 'DirectLabeling-97377357',
        inputs: ['dataObjects', 'labelTask', 'labelSpace'],
        isAlgorithmic: true,
        isBuiltIn: true,
        isModelBased: false,
        isServerless: true,
      },
      x: 265,
      y: 25,
    },
    {
      id: 'node-44216216',
      title: 'grid matrix',
      type: WorkflowNodeType.InteractiveLabeling,
      value: [{
        type: ProcessType.InteractiveLabeling,
        name: 'Grid Matrix',
        id: 'Grid-Matrix',
        inputs: ['dataObjects', 'samples'],
        isAlgorithmic: false,
        isBuiltIn: true,
        isModelBased: false,
        isServerless: true,
        params: {
          nRows: {
            value: 4,
            title: 'Number of Objects per Column',
            options: [
              { value: 1, text: '1' },
              { value: 2, text: '2' },
              { value: 4, text: '4' },
              { value: 6, text: '6' },
              { value: 8, text: '8' },
            ],
          },
          nColumns: {
            value: 4,
            title: 'Number of Objects per Row',
            options: [
              { value: 1, text: '1' },
              { value: 4, text: '4' },
              { value: 8, text: '8' },
              { value: 12, text: '12' },
            ],
          },
        },
      }],
      x: 385,
      y: 25,
    },
    {
      id: 'node-70767097',
      title: 'check all labeled',
      type: WorkflowNodeType.StoppageAnalysis,
      value: {
        type: ProcessType.StoppageAnalysis,
        name: 'AllChecked',
        id: 'AllChecked-46322013',
        inputs: ['labels'],
        isAlgorithmic: true,
        isBuiltIn: true,
        isModelBased: false,
        isServerless: true,
        api: 'AllChecked',
      },
      x: 505,
      y: 25,
    },
    {
      id: 'node-69466632',
      title: 'stop?',
      type: WorkflowNodeType.Decision,
      x: 505,
      y: 115,
    },
    {
      id: 'node-29117539',
      title: 'exit',
      type: WorkflowNodeType.Terminal,
      x: 505,
      y: 205,
    },
  ],
  edges: [
    {
      id: 'edge-78038813',
      source: 'node-47353599',
      target: 'node-6411710',
      x1: 105,
      y1: 55,
      x2: 145,
      y2: 55,
    },
    {
      id: 'edge-79894315',
      source: 'node-6411710',
      target: 'node-63746075',
      x1: 225,
      y1: 55,
      x2: 265,
      y2: 55,
    },
    {
      id: 'edge-23806236',
      source: 'node-63746075',
      target: 'node-44216216',
      x1: 345,
      y1: 55,
      x2: 385,
      y2: 55,
    },
    {
      id: 'edge-41463625',
      source: 'node-44216216',
      target: 'node-70767097',
      x1: 465,
      y1: 55,
      x2: 505,
      y2: 55,
    },
    {
      id: 'edge-25771154',
      source: 'node-70767097',
      target: 'node-69466632',
      x1: 545,
      y1: 85,
      x2: 545,
      y2: 115,
    },
    {
      id: 'edge-15222705',
      source: 'node-69466632',
      target: 'node-29117539',
      x1: 545,
      y1: 175,
      x2: 545,
      y2: 205,
      condition: true,
    },
    {
      id: 'edge-74991592',
      source: 'node-69466632',
      target: 'node-6411710',
      x1: 505,
      y1: 145,
      x2: 180,
      y2: 85,
      condition: false,
    },
  ],
} as WorkflowGraph;
