export const SET_CLASSES = 'SET_CLASSES';
export const SET_SHOW_DATASET_OVERVIEW = 'SET_SHOW_DATASET_OVERVIEW';
export const SET_QUERY_STRATEGY = 'SET_QUERY_STRATEGY';
export const SET_N_BATCH = 'SET_N_BATCH';
export const SET_ITEMS_PER_ROW = 'SET_ITEMS_PER_ROW';
export const SET_ITEMS_PER_COL = 'SET_ITEMS_PER_COL';
