export const SET_SHOW_DATASET_OVERVIEW = 'SET_SHOW_DATASET_OVERVIEW';
export const SET_SAMPLING_STRATEGY = 'SET_SAMPLING_STRATEGY';
export const SET_DEFAULT_LABELING_METHOD = 'SET_DEFAULT_LABELING_METHOD';
export const SET_N_BATCH = 'SET_N_BATCH';
export const SET_ITEMS_PER_ROW = 'SET_ITEMS_PER_ROW';
export const SET_ITEMS_PER_COL = 'SET_ITEMS_PER_COL';
