export const SET_CURRENT_NODE = 'SET_CURRENT_NODE';
export const SET_NODES = 'SET_NODES';
export const SET_EDGES = 'SET_EDGES';
export const SET_DATA_TYPE = 'SET_DATA_TYPE';
export const SET_LABEL_TASKS = 'SET_LABEL_TASKS';
export const SET_MODEL_SERVICES = 'SET_MODEL_SERVICES';
export const SET_PROCESSES = 'SET_PROCESSES';
