import ObjectId from 'bson-objectid';
import {
  ModelService,
  DataObjectSelectionMethod,
  DefaultLabelingMethod,
  FeatureExtractionMethod,
  InteractiveLabelingMethod,
  InterimModelTrainingMethod,
  StoppageAnalysisMethod,
  TaskTransformationMethod,
} from '@/commons/types';
import {
  PROTOCOL,
  IP,
  SERVER_PORT,
} from '@/services/http-params';

export const modelServices: ModelService[] = [{
  name: 'DecisionTree (Supervised)',
  isServerless: false,
  type: 'DecisionTree',
  isBuiltIn: true,
  objectId: (new ObjectId('DecisionTree')).toHexString(),
  usableAsSampler: false,
  // id: 'DecisionTree-95912701',
  // api: `${PROTOCOL}://${IP}:${SERVER_PORT}/model/DecisionTree`,
  // isLocal: true,
}, {
  name: 'SVM (Supervised)',
  isServerless: false,
  type: 'SVM',
  isBuiltIn: true,
  objectId: (new ObjectId('SVM000000000')).toHexString(),
  usableAsSampler: false,
  // id: 'SVM-99885399',
  // api: `${PROTOCOL}://${IP}:${SERVER_PORT}/model/SVM`,
  // isLocal: true,
}, {
  name: 'LogisticRegression (Supervised)',
  isServerless: false,
  type: 'LogisticRegression',
  isBuiltIn: true,
  objectId: (new ObjectId('LogisticRegr')).toHexString(),
  usableAsSampler: true,
  // id: 'LogisticRegression-75095119',
  // api: `${PROTOCOL}://${IP}:${SERVER_PORT}/model/LogisticRegression`,
  // isLocal: true,
}, {
  name: 'RestrictedBoltzmannMachine (Supervised)',
  isServerless: false,
  type: 'RestrictedBoltzmannMachine',
  isBuiltIn: true,
  objectId: (new ObjectId('RestrictedBo')).toHexString(),
  usableAsSampler: false,
  // id: 'RestrictedBoltzmannMachine-73157581',
  // api: `${PROTOCOL}://${IP}:${SERVER_PORT}/model/RestrictedBoltzmannMachine`,
  // isLocal: true,
}, {
  name: 'LabelSpreading (Semi-Supervised)',
  isServerless: false,
  type: 'LabelSpreading',
  isBuiltIn: true,
  objectId: (new ObjectId('LabelSpreadi')).toHexString(),
  usableAsSampler: true,
  // id: 'LabelSpreading-81419641',
  // api: `${PROTOCOL}://${IP}:${SERVER_PORT}/model/LabelSpreading`,
  // isLocal: true,
}];

export const dataObjectSelectionMethods: DataObjectSelectionMethod[] = [{
  name: 'Projection (User Sampling)',
  id: 'Projection',
  inputs: ['features', 'labels'],
  isAlgorithmic: false,
  isBuiltIn: true,
  isServerless: true,
  api: 'Projection',
}, {
  name: 'Random (Dummy)',
  id: 'Random-73417867',
  inputs: ['labels'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: true,
  api: 'Random',
  params: {
    nBatch: {
      value: 48,
      title: 'Selection Batch Size',
      options: [
        { value: 1, text: '1' },
        { value: 4, text: '4' },
        { value: 16, text: '16' },
        { value: 32, text: '32' },
        { value: 48, text: '48' },
        { value: 64, text: '64' },
        { value: 96, text: '96' },
      ],
    },
  },
}, {
  name: 'Cluster (Clustering)',
  id: 'Cluster-13466955',
  inputs: ['features', 'labels'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: false,
  api: `${PROTOCOL}://${IP}:${SERVER_PORT}/selection/Cluster`,
  params: {
    nBatch: {
      value: 48,
      title: 'Selection Batch Size',
      options: [
        { value: 1, text: '1' },
        { value: 4, text: '4' },
        { value: 16, text: '16' },
        { value: 32, text: '32' },
        { value: 48, text: '48' },
        { value: 64, text: '64' },
        { value: 96, text: '96' },
      ],
    },
  },
}, {
  name: 'DenseAreas (Clustering)',
  id: 'DenseAreas-67390401',
  inputs: ['features', 'labels'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: false,
  api: `${PROTOCOL}://${IP}:${SERVER_PORT}/selection/DenseAreas`,
  params: {
    nBatch: {
      value: 48,
      title: 'Selection Batch Size',
      options: [
        { value: 1, text: '1' },
        { value: 4, text: '4' },
        { value: 16, text: '16' },
        { value: 32, text: '32' },
        { value: 48, text: '48' },
        { value: 64, text: '64' },
        { value: 96, text: '96' },
      ],
    },
  },
}, {
  name: 'ClusterCentroids (Clustering)',
  id: 'ClusterCentroids-60587176',
  inputs: ['features', 'labels'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: false,
  api: `${PROTOCOL}://${IP}:${SERVER_PORT}/selection/ClusterCentroids`,
  params: {
    nBatch: {
      value: 48,
      title: 'Selection Batch Size',
      options: [
        { value: 1, text: '1' },
        { value: 4, text: '4' },
        { value: 16, text: '16' },
        { value: 32, text: '32' },
        { value: 48, text: '48' },
        { value: 64, text: '64' },
        { value: 96, text: '96' },
      ],
    },
  },
}, {
  name: 'Entropy (Active Learning)',
  id: 'Entropy-49394355',
  inputs: ['features', 'labels', 'model'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: false,
  api: `${PROTOCOL}://${IP}:${SERVER_PORT}/selection/Entropy`,
  params: {
    nBatch: {
      value: 48,
      title: 'Selection Batch Size',
      options: [
        { value: 1, text: '1' },
        { value: 4, text: '4' },
        { value: 16, text: '16' },
        { value: 32, text: '32' },
        { value: 48, text: '48' },
        { value: 64, text: '64' },
        { value: 96, text: '96' },
      ],
    },
  },
}, {
  name: 'LeastConfident (Active Learning)',
  id: 'LeastConfident-12520162',
  inputs: ['features', 'labels', 'model'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: false,
  api: `${PROTOCOL}://${IP}:${SERVER_PORT}/selection/LeastConfident`,
  params: {
    nBatch: {
      value: 48,
      title: 'Selection Batch Size',
      options: [
        { value: 1, text: '1' },
        { value: 4, text: '4' },
        { value: 16, text: '16' },
        { value: 32, text: '32' },
        { value: 48, text: '48' },
        { value: 64, text: '64' },
        { value: 96, text: '96' },
      ],
    },
  },
}, {
  name: 'SmallestMargin (Active Learning)',
  id: 'SmallestMargin-74021796',
  inputs: ['features', 'labels', 'model'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: false,
  api: `${PROTOCOL}://${IP}:${SERVER_PORT}/selection/SmallestMargin`,
  params: {
    nBatch: {
      value: 48,
      title: 'Selection Batch Size',
      options: [
        { value: 1, text: '1' },
        { value: 4, text: '4' },
        { value: 16, text: '16' },
        { value: 32, text: '32' },
        { value: 48, text: '48' },
        { value: 64, text: '64' },
        { value: 96, text: '96' },
      ],
    },
  },
}, {
  name: 'EntropyDiversity (Active Learning)',
  id: 'EntropyDiversity-98931757',
  inputs: ['features', 'labels', 'model'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: false,
  api: `${PROTOCOL}://${IP}:${SERVER_PORT}/selection/EntropyDiversity`,
  params: {
    nBatch: {
      value: 48,
      title: 'Selection Batch Size',
      options: [
        { value: 1, text: '1' },
        { value: 4, text: '4' },
        { value: 16, text: '16' },
        { value: 32, text: '32' },
        { value: 48, text: '48' },
        { value: 64, text: '64' },
        { value: 96, text: '96' },
      ],
    },
  },
}, {
  name: 'EntropyDiversityDensity (Active Learning)',
  id: 'EntropyDiversityDensity-60957928',
  inputs: ['features', 'labels', 'model'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: false,
  api: `${PROTOCOL}://${IP}:${SERVER_PORT}/selection/EntropyDiversityDensity`,
  params: {
    nBatch: {
      value: 48,
      title: 'Selection Batch Size',
      options: [
        { value: 1, text: '1' },
        { value: 4, text: '4' },
        { value: 16, text: '16' },
        { value: 32, text: '32' },
        { value: 48, text: '48' },
        { value: 64, text: '64' },
        { value: 96, text: '96' },
      ],
    },
  },
}];

export const defaultLabelingMethods: DefaultLabelingMethod[] = [{
  name: 'ModelPrediction',
  id: 'ModelPrediction-29967546',
  inputs: ['features', 'model'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: false,
  api: `${PROTOCOL}://${IP}:${SERVER_PORT}/defaultLabels/ModelPrediction`,
}, {
  name: 'Null (Dummy)',
  id: 'Null-35514905',
  inputs: ['features'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: true,
  api: 'Null',
}, {
  name: 'Random (Dummy)',
  id: 'Random-38398168',
  inputs: ['features'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: true,
  api: 'Random',
}];

export const featureExtractionMethods: FeatureExtractionMethod[] = [{
  name: 'SVD (Unsupervised)',
  id: 'image-SVD-25940167',
  inputs: ['dataObjects'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: false,
  api: `${PROTOCOL}://${IP}:${SERVER_PORT}/features/image/SVD`,
}, {
  name: 'BoW (Handcrafted)',
  id: 'image-BoW-6989392',
  inputs: ['dataObjects'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: false,
  api: `${PROTOCOL}://${IP}:${SERVER_PORT}/features/image/BoW`,
}, {
  name: 'LDA (Supervised)',
  id: 'image-LDA-45100847',
  inputs: ['dataObjects', 'labels'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: false,
  api: `${PROTOCOL}://${IP}:${SERVER_PORT}/features/image/LDA`,
}, {
  name: 'Random3D (Dummy)',
  id: 'Random-87333124',
  inputs: ['dataObjects'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: true,
  api: 'Random3D',
}];

export const interactiveLabelingMethods: InteractiveLabelingMethod[] = [{
  name: 'Single Object Display',
  id: 'Single-Object-Display',
  inputs: ['dataObjects', 'samples'],
  isAlgorithmic: false,
  isBuiltIn: true,
  isServerless: true,
}, {
  name: 'Grid Matrix',
  id: 'Grid-Matrix',
  inputs: ['dataObjects', 'samples'],
  isAlgorithmic: false,
  isBuiltIn: true,
  isServerless: true,
  params: {
    nRows: {
      value: 6,
      title: 'Number of Objects per Column',
      options: [
        { value: 1, text: '1' },
        { value: 2, text: '2' },
        { value: 4, text: '4' },
        { value: 6, text: '6' },
        { value: 8, text: '8' },
      ],
    },
    nColumns: {
      value: 8,
      title: 'Number of Objects per Row',
      options: [
        { value: 1, text: '1' },
        { value: 4, text: '4' },
        { value: 8, text: '8' },
        { value: 12, text: '12' },
      ],
    },
  },
}];

export const interimModelTrainingMethods: InterimModelTrainingMethod[] = [{
  name: 'Retrain',
  id: 'Retrain-16440841',
  inputs: ['features', 'labels', 'model'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: false,
  api: `${PROTOCOL}://${IP}:${SERVER_PORT}/modelUpdated/Retrain`,
}, {
  name: 'Static',
  id: 'Static-72885436',
  inputs: ['model'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: true,
  api: 'Static',
}];

export const stoppageAnalysisMethods: StoppageAnalysisMethod[] = [{
  name: 'AllChecked',
  id: 'AllChecked-46322013',
  inputs: ['labels'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: true,
  api: 'AllChecked',
}];

export const taskTransformationMethods: TaskTransformationMethod[] = [{
  name: 'DirectLabeling',
  id: 'DirectLabeling-97377357',
  inputs: ['dataObjects', 'labelTask', 'labelSpace'],
  isAlgorithmic: true,
  isBuiltIn: true,
  isServerless: true,
  api: 'DirectLabeling',
}];
